FROM node:22-alpine

ENV APP_PORT 3000
ENV NODE_ENV development
ENV WORKDIR_APP /app

WORKDIR ${WORKDIR_APP}

COPY package.json .

RUN npm install

COPY . .

EXPOSE ${APP_PORT}

CMD ["npm", "run", "start:dev"]